### ISSUE TITLE
Cannot disable admin notification Emails for auto-approved accounts

### ISSUE THREAD

**Issue by jalovick** [tendenci/tendenci#1143]
For account types that have the auto-approve option set, a notification Email is sent to verify that an account has been approved. We feel this is redundant, as there is also an Email to notify that a new account has been setup. Is it possible to disable notification Emails for accounts that are set to auto-approve?

We're running Tendenci 14.3.2, and I believe the module is "Membership Application". The Email sent has a subject of <organisation> - Membership application approved <Full Name>

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/8c64981211c84529720d069f81e5ff0ed4ab20b5. Thanks @jalovick !

**Comment by jalovick** [comment]
Hi,

We applied the updated version, but am still getting the Email. Are there any additional settings that need to be changed?

Thanks

Jamie

**Comment by jennyq** [comment]
Hi Jamie,

For new users, those two emails are different. The first one is a welcome email to let user know that an account has been created for them, and how they can log in. The second one is the notification telling them their memberships have been approved. We think both are necessary, but if you really want to git rid of the second email, at the admin backend /admin/memberships/notice/, find the one that says "When to Send: 0 days At Time of Join Approval Date", and set its "Status detail" to "Admin Hold". Note that this would also prevent the existing users from receiving the approval notice. 
 
Best,
Jenny
