### ISSUE TITLE
Is this the correct way to filter Directories?

### ISSUE THREAD

**Issue by b-davies24** [tendenci/tendenci#1249]
After upgrading to >=14.8, our filtering code (designed to not show Directories tagged with "Conversionbook" or "classifieds" on a box on the website's homepage) has stopped working.
Would this be the correct way to filter out these tags?

```
<ul class="list-unstyled">
        {% list_directories as directories_list random=true limit=1 tags!="Conversionbook, classifieds"%}
        {% if "conversionbook" not in directory.tags|lower  and 'classifieds' not in directory.tags|lower %}
        {% for directory in directories_list%}
        
           <div class="thumbnail panel panel-default" style="border-style: hidden; ">
             <p class="story-title"> <b> <a href="{{ directory.get_absolute_url }}">{{ directory.headline|safe}}</a></b></p>
             <div class="zoom" style="height: 250px;">
               <a href="{{ directory.get_absolute_url }}">
               <img class="img-responsive" src="{{ directory.get_logo_url }}" alt="{{ directory.headline }}"  style="max-height:250px; margin: auto;" >
               </a>  
             </div>
           <p class="story-summary">{{ directory.summary|striptags|safe|truncatechars:"150"}} <a href="{{ directory.get_absolute_url }}"><br>Find out more</a> </p>
           </div>   
         
         {% endfor %}
         {% endif %}
         
      </ul>  
```
The box with this code is currently showing ALL Directories, where it previously would filter out the two previously mentioned tags in Tendenci <14.8

**Comment by jennyq** [comment]
The if statement needs to be moved in the for loop. Try this:

    <ul class="list-unstyled">
        {% list_directories as directories_list random=true %}
        {% for directory in directories_list %}
         {% if "conversionbook" not in directory.tags|lower  and 'classifieds' not in directory.tags|lower %}
           <div class="thumbnail panel panel-default" style="border-style: hidden; ">
             <p class="story-title"> <b> <a href="{{ directory.get_absolute_url }}">{{ directory.headline|safe}}</a></b></p>
             <div class="zoom" style="height: 250px;">
               <a href="{{ directory.get_absolute_url }}">
               <img class="img-responsive" src="{{ directory.get_logo_url }}" alt="{{ directory.headline }}"  style="max-height:250px; margin: auto;" >
               </a>  
             </div>
           <p class="story-summary">{{ directory.summary|striptags|safe|truncatechars:"150"}} <a href="{{ directory.get_absolute_url }}"><br>Find out more</a> </p>
           </div>   
           {% endif %}
         {% endfor %}      
      </ul>

**Comment by b-davies24** [comment]
Thank you. This has fixed the filtering, however, has also brought to light a second problem:
Occasionally, when I assume a "conversionbook"/"classifieds" tag is selected, it will leave the space blank (see attached homepage image below - right third should be another directory):
![image](https://github.com/tendenci/tendenci/assets/156738991/820599cc-2c21-426a-b581-d092f4653f8c)


This is also repeated on Tendenci's 'Directories' page, where our filtering code works correctly, but will leave spaces empty (one example attached of Directories page - in middle row, two blank spaces):
![image](https://github.com/tendenci/tendenci/assets/156738991/449fa4ae-2002-493b-81e8-a9ab6df06085)

I can attach more of our code, if this helps, but since this occurs whenever attempting to filter, it may be a wider issue. Is there a way to filter directories without creating these blank spaces?

**Comment by jennyq** [comment]
Looks like there is a css issue on directories search. We'll look into it.

**Comment by jennyq** [comment]
The issue has been fixed after forcing the height to be the same for each directory panel.  https://github.com/tendenci/tendenci/commit/bce5eddfc754958d3e7c88c4fb1d1147d911f8dd

**Comment by b-davies24** [comment]
@jennyq we are still facing the same issue, despite the changes. Attached are our custom changes from the Search page: 

1. `{% load box_tags %}` - added at top

2. ` 
      {% box 35 %} ` - Changes to a custom text that we display on the page

`    <section class="clearfix">
        {% for directory in directories %}
           {% if request.user.is_superuser %} 
              {% search_result directory %}
           {% else %}
               {% if "conversionbook" not in directory.tags|lower and 'classifieds' not in directory.tags|lower %}
                   {% search_result directory %}
               {% endif %}
            {% endif %}
       {% empty %}
            {% if user.profile.is_superuser %}
                <p><a href="{% url 'directory.add' %}">
                    {% if MODULE_DIRECTORIES_LABEL %}
                        {% blocktrans %}
                            Add a New {{ MODULE_DIRECTORIES_LABEL }}
                        {% endblocktrans %}
                    {% else %}
                        {% trans "Add a New Directory" %}
                    {% endif %}
                </a></p>
            {% endif %}
        {% endfor %}
    </section>` - Added to filter directories (i.e. the same part of code as previously listed)

4. JavaScript at bottom of page has // removed from each line.

Would any of these lines of code interfere with the changes you made?

**Comment by jennyq** [comment]
It doesn't look like those lines of code would interfere with the changes we made. 

Have you tried to back up and delete your customized directories/search.html to see if your format issue is gone? After that, you can re-pull and customize it.

**Comment by b-davies24** [comment]
After deleting the custom search.html, there are no formatting errors (as expected - the hidden directories are showing):

![Screenshot 2024-03-05 at 14-54-53 Directories List - Australian Electric Vehicle Association Directories for AEVA in Australia](https://github.com/tendenci/tendenci/assets/156738991/08dba69a-ea02-4304-b4e4-5e78bbf19a3d)

After re-pulling search.html and changing the `<section>` code to 
`<section class="clearfix"> {% for directory in directories %} {% if request.user.is_superuser %} <!-- added to remove classifieds from normal users --> {% search_result directory %} {% else %} {% if "conversionbook" not in directory.tags|lower and 'classifieds' not in directory.tags|lower %} {% search_result directory %} {% endif %} {% endif %} {% empty %} {% if user.profile.is_superuser %} <p><a href="{% url 'directory.add' %}"> {% if MODULE_DIRECTORIES_LABEL %} {% blocktrans %} Add a New {{ MODULE_DIRECTORIES_LABEL }} {% endblocktrans %} {% else %} {% trans "Add a New Directory" %} {% endif %} </a></p> {% endif %} {% endfor %} </section>`
The problem persists - the hidden directory still takes space, and that appears blank:

![Screenshot 2024-03-05 at 14-58-15 Directories List - Australian Electric Vehicle Association Directories for AEVA in Australia](https://github.com/tendenci/tendenci/assets/156738991/cfd9c7e0-2237-4969-955d-ff72d2ac4664)

This seems similar to the previously mentioned issue with the homepage directories (post on 23rd Jan), where the system appears to select/show a hidden directory, then just replace it with blank space.

How can this be avoided?

**Comment by b-davies24** [comment]
I just remembered another symptom: when you search through directories, for example, beginning with "K", it will state "x Directories Found" ← this calculation includes the hidden ones. I think this is tied in with the blank-space-replacement.
![image](https://github.com/tendenci/tendenci/assets/156738991/ae5bd77c-4498-4905-8817-9c17efedc607)

**Comment by jennyq** [comment]
Looks like you don't want regular users to see those directories with the tags "conversionbook" and "classifieds". 

To resolve the issue, you can simply change the permissions of those directories - uncheck "Public can view" and any other checkboxes for users and members. That is better than hiding them in search as they wouldn't be able to access even if they somehow get the links of those directories.

**Comment by b-davies24** [comment]
Thank you for your response. We want everyone to be able to see "conversionbook" and "classifieds" tagged items, however, only on their respective pages. Currently, there is a separate page that shows all "conversionbook" tagged items, and the search.html page shows all the other directories (currently with the strange formatting due to the aforementioned code). 
How would you suggest we split directories into different pages? Could some permission be changed so that "conversionbook" directories only show on one page, and nowhere else?

**Comment by jennyq** [comment]
To show only "conversionbook" directories, you can use this url:
/directories/?q=tag:conversionbook

**Comment by b-davies24** [comment]
Thank you for responding. Currently, the problem occurs when we want to 'show everything _except_ xxx', rather than 'show _only_ xxx'. We have set up a page to only show Conversionbook (which works fine): https://aeva.asn.au/conversionbook/ 
We want the base Directories (search.html) to show everything except "conversionbook" - this is where the formatting problems arise. We are essentially trying to create 2 separate 'directory' groups, so that only the non-Conversionbook items show on the https://aeva.asn.au/directories/ page, and the Conversionbooks on the /conversionbook page.

Would it be better to tag everything other than Conversionbook with some tag, and then create another page that shows only this tag? Do you have any other suggestions for how to do this?

**Comment by jennyq** [comment]
Yes, you can certainly tag everything other than Conversionbook.

There is another way, but it would need some programming on your end. You can create a template filter to exclude directories with the tag Conversionbook.

**Comment by rob-hills** [comment]
I've had a go at this, adding a filter to /tendenci/tendenci/apps/filters/templatetags/directory_filters.py [here](https://github.com/rob-hills/tendenci/blob/6282d120e7c68783a375b5427ea4a1fc464cc73c/tendenci/apps/directories/templatetags/directory_filters.py#L33)

I've made it a "has_tag" filter that takes a directory and a tag, thinking to make it more widely applicable than the immediate problem at hand but it all seems too simple to me.  However, all the other filters in this module seem equally simple!

Looking at how the other filters are used, I'm assuming @b-davies24 would use something like
```
{% if not directory|has_tag:"conversionbook" %}
```
in his template?

For @b-davies24 : My code change is currently only in my GitHub repository.  If @jennyq thinks it looks like it might work then I'll put it on our test server so you can try it out.

**Comment by rob-hills** [comment]
This morning I've propagated my directory_filters code tweak to our [test site](https://test.aeva.asn.au).

I've updated the code in the homepage template to use these, replacing:
```
     {% if "conversionbook" not in directory.tags|lower  and 'classifieds' not in directory.tags|lower %}
```
with

```
     {% if not directory|has_tag:"conversionbook" and not directory|has_tag:"classifieds" %}
```

While the revision looks neater, it's not clear to me how the logic is any different.  

@b-davies24 this renders the  homepage OK so that's a good start, however, after a couple of refreshes I've now seen one of the "gaps" appear in the Directory Listing section near the bottom, either side of the "We have branches in every state" section.  So as I suspected, the code change looks neater but hasn't fixed the logic problem yet!

**Comment by rob-hills** [comment]
OK, I understand the problem now.  The Template code is only filling the space **_if_** the current directory entry in the list doesn't have the tags we want to exclude.  So this logic will always produce blank spaces.

We need to modify the directory_list code to be able to produce a list of directories that **_don't have_** tags we want to exclude.

**Comment by rob-hills** [comment]
@jennyq it seems to me that the neatest fix for our problem would be to add an "excludes_tags" parameter to the ListNode class in /tendenci/tendenci/apps/base/template_tags.py, using similar logic to that dealing with the tags parameter starting at [line 203](https://github.com/tendenci/tendenci/blob/f3f49d1b37c33af88e36b6ae96528795987d0f71/tendenci/apps/base/template_tags.py#L203).

However as that is deep into the core functionality, I don't want to go messing with it unless you agree it's likely to be the best way to solve our problem.  I believe it would be useful generally to be able to produce lists that exclude certain tags anyway.

**Comment by jennyq** [comment]
@rob-hills, I've added a template filter `exclude_tags` to core https://github.com/tendenci/tendenci/commit/c83d617fc3a82385ba63b9cbf9eb042d52001ffe. 

To use this filter, in your directories/search.html, add this line at the top:

    {% load directory_filters %}

Then, wrap everything starting from `autopaginate` to `paginate` in a `with` statement:

    {% with directories|exclude_tags:"classifieds,conversionbook" as directories %}
    {% autopaginate directories 10 %}
    {% directory_search %}
    
        ....
     
    {% paginate %}
    {% endwith %}   


It should work for you now.

**Comment by rob-hills** [comment]
Many thanks for the exclude_tags change @jennyq 

Unfortunately, we need to use the list_directories tag to obtain a single directory at random:

`{% list_directories as directories_list limit=1 random=true  %}`

Is there a way of using your filter with the "list_directories" tag?  I've tried several variations like this:
`{% list_directories as directories_list limit=1 random=true |exclude_tags:"classifieds,conversionbook" %}`

but the variations I've tried either trigger an exception, or else render the page, but don't actually filter the list (ie the directories returned include those tagged "classified" and/or "conversionbook".

**Comment by jennyq** [comment]
The `exclude_tags` filter doesn't work with `list_directories`. 

You can do this `{% list_directories as directories_list limit=1 random=true exclude="5,6,7,9"  %}`, where "5,6,7,9" are IDs of the directories you want to exclude.

**Comment by rob-hills** [comment]
Unfortunately, we don't know the IDs of the directories we want to exclude, just the ones that have specific tags.  I need to see if I can work out how to add an "exclude_tags" option to the list_directories tag

**Comment by rob-hills** [comment]
@jennyq I have submitted a pull request for this issue( #1294 ), hopefully you can use this.

**Comment by jennyq** [comment]
@rob-hills I'll review it. Thanks!
