### ISSUE TITLE
Menu unreadable in Mobile format

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#873]
In mobile screen format, the menus go to hamburgers.
This is fine with the main menu, but the new one that appears when you log in doesn't work properly.  All the options are there, but they seem to have a clear background, which makes them very difficult to read.
I've tried this on our site (12.0.10) and the demo site (12.0.7).

![Mobile_Menu](https://user-images.githubusercontent.com/64681720/87355242-64d14980-c5a3-11ea-973a-b6f441452ef0.png)

**Comment by ediaz1** [comment]
Thank you for reporting this is now fixed.

**Comment by CWalkden** [comment]
We've just upgraded to 12.0.13 on our test server, and this issue is still apparent.
![Screenshot at 2020-08-10 08-58-51](https://user-images.githubusercontent.com/64681720/89743578-d12e6280-dae7-11ea-8ade-8981428a1c5b.png)

**Comment by jennyq** [comment]
Hi @CWalkden, it doesn't affect the existing sites that don't have the admin_menu.css included. To fix for your site, in your theme editor at /theme-editor/editor/?file=media/css/base.css, you can copy the code [here](https://github.com/tendenci/tendenci/blob/4ae535181fb525e8367fd48df83fae9995fccf35/tendenci/themes/t7-tendenci2020/media/css/base.css#L223) from Ln 223 to Ln 267 to your base.css.
