### ISSUE TITLE
TinyMCE bug in Events module

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#988]
When editing an Event Organizer, the TinyMCE window is not shown properly.  It is truncated, and won't maximise.
![Screenshot at 2021-02-18 08-41-24](https://user-images.githubusercontent.com/64681720/108271581-22b95780-71c5-11eb-843f-442d41bd04af.png)

**Comment by jennyq** [comment]
@CWalkden, 

Resolved https://github.com/tendenci/tendenci/commit/401249cc96ba48c1a59fc204218e25970f786dd1. Thank you for pointing it out! To fix for your site, please update the corresponding media/css/base.css in your theme editor. Just remove or comment out these lines:

    #page-top iframe#id_organizer-description_ifr,
    #page-top iframe#id_place-description_ifr,
    iframe#speaker-0-description_ifr {
        height: 100px !important;
    }

**Comment by CWalkden** [comment]
Hi @jennyq,
We just upgraded our test site to 12.4.7, and this bug is still there.
Should that have fixed it, or do we also need to do what you wrote above?

**Comment by CWalkden** [comment]
Ok, it turns out that we had customised that file, so it wasn't updated with the upgrade.  We've applied the code now and all is working well.
